version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'flightbooking'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./db:/db
      - ./db/DB-setup.sql:/docker-entrypoint-initdb.d/DB-setup.sql
      - db-data:/var/lib/mysql
  api:
    build: ./api
    command: python app.py
    volumes:
      - ./api:/app
    ports:
      - '5001:5000'
    depends_on:
      - db

volumes:
  db-data:
